### PR TITLE
feat: add fastcc with test

### PR DESCRIPTION
**Pull request by synchon**
- adds FASTCC
- will open separate PR for FASTCORE

### CODE REVIEW

**Comment by Midnighter** [comment]
Since the fastcc toy model will only be used in the `test_fastcc.py` module, I would move it there from the `conftest.py`.

**Review by Midnighter — CHANGES_REQUESTED** [review]
Since the fastcc toy model will only be used in the `test_fastcc.py` module, I would move it there from the `conftest.py`. Other than that it looks like a very nice and clean PR :+1:

**Comment by synchon** [comment]
Once FASTCORE gets added, it will also share the same model. Keeping that in mind, I placed it there. Do you still want me to move it?

**Comment by Midnighter** [comment]
No, that's perfect then.

**Review by Midnighter — APPROVED** [review]

**Comment by synchon** [comment]
Awesome! 👍

**Pull request merged**
